# 其他项目不依赖时用 test 其他项目依赖时用 install，
variables:
  phase: test -Dmaven.compiler.failOnError=false -Dmaven.test.failure.ignore=true
#  phase: install -Dmaven.compiler.failOnError=false -Dmaven.test.failure.ignore=true

# 顶级群组环境变量（保护+隐藏）
# sonarLogin=
# 顶级群组环境变量
# sonar_server=-Dsonar.host.url=http://ip:port -Dsonar.login=${sonarLogin}
# MAVEN_CLI_OPTS=-V -U -fae -DinstallAtEnd=true -DdeployAtEnd=true
# Maven 命令行参数官方文档：http://maven.apache.org/ref/3.6.3/maven-embedder/cli.html

sonar:
  stage: build
  script:
    - if [ ! -f pom.xml ]; then
        if [ "$sonar_server" != "" ]; then
          sonar-scanner
            -Dsonar.sources=. -Dsonar.java.binaries=.
            -Dsonar.projectName="$CI_PROJECT_PATH $CI_PROJECT_PATH_SLUG scanner"
            -Dsonar.projectKey=${CI_PROJECT_PATH_SLUG}
            $sonar_server;
        fi;
      else
        if [ -f ci_settings.xml ]; then
          setting_file="-s ci_settings.xml";
        fi;

        prepare_phase = "org.jacoco:jacoco-maven-plugin:prepare-agent";
        report_phase = "org.jacoco:jacoco-maven-plugin:report";
        sonar_phase = "org.sonarsource.scanner.maven:sonar-maven-plugin:sonar";

        if [ "$sonar_server" != "" ]; then
          mvn $MAVEN_CLI_OPTS $setting_file $prepare_phase $phase $report_phase $sonar_phase
            -Dsonar.projectName="$CI_PROJECT_PATH $CI_PROJECT_PATH_SLUG"
            -Dsonar.projectKey=$CI_PROJECT_PATH_SLUG
            $sonar_server;
        else
          mvn $MAVEN_CLI_OPTS $setting_file $prepare_phase $phase $report_phase;
        fi;
      fi
#  only:
#    - master
#  except:
#    - master
